# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuideNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ZKCarousel'

  # Pods for GuideNews

  target 'GuideNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuideNewsUITests' do
    # Pods for testing
  end

end
